version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crypto
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    command: pnpm dev
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - 3333:3333

#  nuxt:
#    build:
#      context: ./front
#      dockerfile: Dockerfile
#    restart: always
#    volumes:
#      - ./front:/app
#    ports:
#      - 3000:3000
